language: php

cache:
    directories:
      - "$HOME/.composer/cache"
      - "$HOME/.npm"

matrix:
  fast_finish: true
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
    - php: '7.2'
      env: COVERAGE=yes

services:
  - mongodb

before_install:
  - sudo apt-get update > /dev/null
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
  - phpenv config-rm xdebug.ini

install:
  # install php packages required for running YAWIK phpunit tests
  - sudo apt-get install -y --force-yes php5-intl php5-curl php5-xsl

  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  # install Mongo extension
  - pecl channel-update pecl.php.net
  - pecl install -f mongodb-stable
  - pecl install -f solr-2.4.0

  - phpenv config-add .travis/phpenv.ini
  - curl -sS https://getcomposer.org/installer | php
  - ./composer.phar self-update
  - ./composer.phar create-project --stability dev cross-solution/yawik=dev-develop ../yawik
  # Solr directory still exists in 0.27.2
  - rm -Rf `dirname $TRAVIS_BUILD_DIR`/yawik/module/Orders
  - mv ../`basename $TRAVIS_BUILD_DIR` `dirname $TRAVIS_BUILD_DIR`/yawik/module

script:
  - cd `dirname $TRAVIS_BUILD_DIR`/yawik/module/Orders/test
  - 'if [[ $COVERAGE = yes ]]; then
        ./vendor/bin/phpunit -c test --verbose --coverage-clover=build/logs/clover.xml --coverage-php=build/logs/clover.serialized;
    else
        ./vendor/bin/phpunit -c test --verbose;
    fi'

after_script:
  - 'if [[ $COVERAGE = yes ]]; then
        cd `dirname $TRAVIS_BUILD_DIR`/yawik/module/Orders
        php `dirname $TRAVIS_BUILD_DIR`/yawik/vendor/bin/coveralls -vvv
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.serialized
    fi'