language: php

cache:
    directories:
      - "$HOME/.composer/cache"
      - "$HOME/.npm"

env:
  global:
    - PECLMONGO="mongodb-stable"

matrix:
  fast_finish: true
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
      env: COVERAGE=yes

services:
  - mongodb

before_install:
  - sudo apt-get update > /dev/null
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi;
  - pecl channel-update pecl.php.net

install:
  # install php packages required for running YAWIK phpunit tests
  - pecl install -f ${PECLMONGO}
  - phpenv config-add .travis/phpenv.ini
  - composer install
  - ./vendor/bin/yawik assets:install --relative
  - yarn install

script:
  - 'if [[ $COVERAGE = yes ]]; then
        ./phpunit --verbose --coverage-clover=build/logs/clover.xml --coverage-php=build/logs/clover.serialized;
    else
        ./phpunit --verbose;
    fi'

after_script:
  - 'if [[ $COVERAGE = yes ]]; then
        composer require php-coveralls/php-coveralls;
        travis_retry php-coveralls -vvv;
        wget https://scrutinizer-ci.com/ocular.phar;
        travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.serialized;
    fi'