language: php

cache:
    directories:
      - "$HOME/.composer/cache"
      - "$HOME/.npm"

env:
  global:
    - PECLMONGO="mongodb-stable"

matrix:
  fast_finish: true
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
      env: COVERAGE=yes

services:
  - mongodb

before_install:
  - sudo apt-get update > /dev/null
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi;
  - pecl channel-update pecl.php.net

install:
  # install php packages required for running YAWIK phpunit tests
  - sudo apt-get install -y --force-yes php5-intl php5-curl php5-xsl

  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - if [[ $COVERAGE = yes ]]; then composer global require php-coveralls/php-coveralls; fi;

before_script:
  # install Mongo extension
  - pecl install -f ${PECLMONGO}

  - phpenv config-add .travis/phpenv.ini
  - composer create-project --stability dev cross-solution/yawik=dev-develop ../yawik
  - mv $TRAVIS_BUILD_DIR ../yawik/module/Orders

script:
  - cd `dirname $TRAVIS_BUILD_DIR`/yawik/module/Orders/test
  - 'if [[ $COVERAGE = yes ]]; then
        ./phpunit --verbose --coverage-clover=build/logs/clover.xml --coverage-php=build/logs/clover.serialized;
    else
        ./phpunit --verbose;
    fi'

after_script:
  - 'if [[ $COVERAGE = yes ]]; then
        cd `dirname $TRAVIS_BUILD_DIR`/yawik;
        travis_retry php-coveralls -vvv;
        wget https://scrutinizer-ci.com/ocular.phar;
        travis_retry php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.serialized;
    fi'